p='docs/traces/recette-personas/lot1/executer-passe2.mjs'
s=open(p).read().replace("import {readFile,writeFile,mkdir}","import pg from 'pg';\nimport {readFile,writeFile,mkdir}")
s=s.replace("const actions={};", "process.env.RACINE_FICHIERS=process.cwd()+'/docs/traces/recette-personas/lot1/fichiers';\nconst actions={};")
s=s.replace("const meta=JSON.parse(await readFile(inst,'utf8'));", """const meta=JSON.parse(await readFile(inst,'utf8'));
if([19,20,23].includes(n)){
 const pool=new pg.Pool({host:meta.env.HOTE_BASE??meta.env.HOTE_POSTGRES??'127.0.0.1',port:Number(meta.env.PORT_BASE??meta.env.PORT_DB??19432),user:meta.env.UTILISATEUR_BASE??meta.env.UTILISATEUR_POSTGRES??'codicillus',password:meta.env.MDP_BASE??meta.env.MDP_POSTGRES,database:meta.base});
 if(n===19){const content=[];for(let k=1;k<=5;k++){content.push({type:'heading',attrs:{level:k===2?3:2},content:[{type:'text',text:'Section polaire '+k}]});for(let j=0;j<8;j++)content.push({type:'paragraph',content:[{type:'text',text:('Diagnostic de la section '+k+' : examiner le relais. ').repeat(8)}]});}await pool.query("update notes set corps_reference=$1 where identifiant='recette-interne'",[JSON.stringify({type:'doc',content})]);}
 if(n===23)await pool.query("insert into templates(identifiant,nom,description,type_de_note_id,structure,contenu) values('guide-polaire','Guide polaire','Structure de diagnostic de recette',(select id from types_de_note where identifiant='guide'),'[]',$1)",['## Diagnostic polaire\\n\\nContrôler la passerelle australe.']);
 if(n===20){const {rows:[f]}=await pool.query("insert into pieces_jointes(note_id,nom,taille_octets,type_media) select id,'diagnostic-polaire.txt',18,'text/plain' from notes where identifiant='recette-interne' returning id,note_id");await mkdir(meta.env.RACINE_FICHIERS+'/'+f.note_id,{recursive:true});await writeFile(meta.env.RACINE_FICHIERS+'/'+f.note_id+'/'+f.id,'Diagnostic polaire');}
 await pool.end();a.push({assertion:'Prérequis second jeu établi avant navigation (note longue / template / fichier selon parcours)',ok:true});
}
""")
s=s.replace("await cli(t.p,'button',/^Créer$/)","await cli(t.p,'button','Créer le dossier')")
s=s.replace("await cli(t.p,'link',/Droits|Gérer les droits/)","await cli(t.p,'button','Gérer les droits')")
s=s.replace("actions[15]=async t=>{await dossier(t);", "actions[15]=async t=>{await dossier(t);await cli(t.p,'link','Relève boréale');await t.snap('dossier-enfant');")
s=s.replace("actions[19]=async t=>{await t.snap('sommaire');await check(t,'Sommaire absent en absence de titre',!await visible(t.p,/SOMMAIRE/));manque(t,'Note longue non disponible dans le décor : navigation vers section longue non exercée');};", """actions[19]=async t=>{await t.snap('sommaire');await cli(t.p,'link','Section polaire 4');await t.p.waitForTimeout(700);await t.snap('section-visee');await check(t,'Clic sommaire amène à section 4',await t.p.getByRole('heading',{name:'Section polaire 4',exact:true}).evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.top<600;}));await t.go('/notes/recette-publique');await check(t,'Sommaire absent sans titre',!await visible(t.p,/SOMMAIRE/));};""")
s=s.replace("actions[20]=async t=>{await t.snap('pieces-jointes');await check(t,'Fichier téléchargeable disponible',await t.p.getByRole('link',{name:/Télécharger/}).count()>0);manque(t,'Aucune pièce jointe dans décor, téléchargement et droits anonyme non exercés');};", """actions[20]=async t=>{await t.snap('pieces-jointes');const l=t.p.getByRole('link',{name:/diagnostic-polaire.txt/});const download=t.p.waitForEvent('download');await l.click();const f=await download;await f.saveAs('docs/traces/recette-personas/PAR-020/diagnostic-telecharge.txt');await check(t,'Octets fichier récupérés',await readFile('docs/traces/recette-personas/PAR-020/diagnostic-telecharge.txt','utf8')==='Diagnostic polaire');manque(t,'Droit anonyme sur adresse directe non exercé dans ce contexte authentifié');};""")
s=s.replace("actions[23]=async t=>{await nouveau(t);await t.snap('templates');await check(t,'Sélecteur template visible',await t.p.locator('input[name=template]').isVisible());manque(t,'Aucun template disponible dans le décor ; choix aperçu contenu et type non exercés');};", """actions[23]=async t=>{await nouveau(t);await t.snap('templates');await cli(t.p,'button',/Guide polaire/);await t.snap('template-choisi');await check(t,'Contenu et type préremplis',await visible(t.p,/Diagnostic polaire/));await t.p.getByPlaceholder('Titre de la note',{exact:true}).fill('Guide polaire publié');await t.p.locator('input[name="choix-de-dossier"]').last().check();await enregistrer(t);await check(t,'Contenu template publié',await visible(t.p,/Contrôler la passerelle australe/));};""")
open(p,'w').write(s)
