p='docs/traces/recette-personas/lot1/executer-passe2.mjs';s=open(p).read()
s=s.replace("'_a2`", "'_a2r`") if False else s.replace('_a2`','_a2r`').replace('passe-2','passe-2-reprise')
s=s.replace("let index=0;await Promise.all([0,1].map(async()=>{while(index<38){const n=++index;await run(n);}}));", "const selection=process.argv.slice(2).map(Number);let index=0;await Promise.all([0,1].map(async()=>{while(index<selection.length){const n=selection[index++];await run(n);}}));")
s=s.replace(".fill(q);await t.p.waitForTimeout(650)",".fill(q);await t.p.getByLabel('Requête de recherche',{exact:true}).press('Enter');await t.p.waitForTimeout(900)")
s=s.replace("attrs:{level:k===2?3:2}","attrs:{level:k===2?3:2,ancre:'section-polaire-'+k}")
s=s.replace("name:/diagnostic-polaire.txt/", "name:/diagnostic-polaire/")
s=s.replace("const download=t.p.waitForEvent('download');await l.click();const f=await download;", "const [f]=await Promise.all([t.p.waitForEvent('download'),l.click()]);")
s=s.replace("await cli(t.p,'button','Signaler à réviser');await t.snap('demande');", "await t.p.locator('#btn-reviser-envoi').click();await t.p.waitForTimeout(700);await t.snap('demande');")
s=s.replace("await proc.check();", "await proc.click({noWaitAfter:true});")
s=s.replace("await cli(t.p,'button',/Guide polaire/);", "await t.p.getByLabel(/Guide polaire/).check();")
s=s.replace("manque(t,'Toutes constructions de barre et menu étendu non exercées');", "await cli(t.p,'link','Modifier');await cli(t.p,'button','Menu étendu');for(const label of ['Diagramme','Lien interne',\"Bloc d’alerte\"]){await check(t,'Commande '+label,await visible(t.p,new RegExp(label.replace('’',\"'\"),'i')));}await t.snap('menu-etendu');")
s=s.replace("await cli(t.p,'button',/Relève du relais boréal/);", "await t.p.keyboard.press('Escape');await cli(t.p,'button','Menu étendu');await cli(t.p,'button','Lien interne');await t.snap('dialogue-lien');const champ=t.p.getByRole('textbox').filter({visible:true}).last();await champ.fill('Relève');await t.p.waitForTimeout(700);await cli(t.p,'button',/Relève du relais boréal/);")
open('docs/traces/recette-personas/lot1/reprise.mjs','w').write(s)
